### ISSUE TITLE
Update GH Actions to push alpine image

### ISSUE THREAD

**Issue by MAGICCC** [icedream/docker-ts3server#28]
Currently only the [Dockerfile](https://github.com/icedream/docker-ts3server/blob/main/Dockerfile) will be used to build and push to Dockerhub. An update to the action file is neccessary to do the same for the [alpine.Dockerfile](https://github.com/icedream/docker-ts3server/blob/main/alpine.Dockerfile)

**Comment by icedream** [comment]
Workflows have been updated to build both Alpine and Debian images, with the newest version being retagged to trigger the missing Alpine build.

All previous Alpine Docker images have also been pushed to GitHub Container Registry.
